export const PC_QUESTIONS = [
  {
    id: 'pc1', n: 1, type: 'single',
    meta: 'Panic Cycle — Trigger',
    q: 'What type of situation most often starts your cycle?',
    sub: 'Select one.',
    choices: [
      'Making a visible mistake in a game',
      'Underperforming compared to expectations',
      'Conflict or tension with a teammate or coach',
      'Fear of losing my starting position or playing time',
      'High-pressure moments (playoffs, tryouts, big games)',
      'Feeling like I\'m not improving fast enough',
    ],
  },
  {
    id: 'pc2', n: 2, type: 'multi', max: 2,
    meta: 'Panic Cycle — First Signal',
    q: 'When this happens, what is the first thing you notice?',
    sub: 'Choose up to two.',
    choices: [
      'A rush of heat or tension in my body',
      'My mind goes blank or starts racing',
      'I become hyperaware of what others think',
      'I want to disappear or withdraw',
      'I feel an urge to fix it immediately',
      'I go quiet and pull inward',
    ],
  },
  {
    id: 'pc3', n: 3, type: 'multi', max: 2,
    meta: 'Panic Cycle — Emotions',
    q: 'Which emotions feel closest in those moments?',
    sub: 'Choose up to two.',
    choices: [
      'Shame or embarrassment',
      'Anxiety or dread',
      'Anger or frustration',
      'Sadness or defeat',
      'Numbness or disconnection',
      'Desperation to get back on track',
    ],
  },
  {
    id: 'pc4', n: 4, type: 'single',
    meta: 'Panic Cycle — Inner Voice',
    q: 'What is your most common automatic thought?',
    sub: 'Select one.',
    choices: [
      '"I\'m letting everyone down"',
      '"I need to fix this right now"',
      '"I\'m not good enough to be here"',
      '"Everyone is watching and judging me"',
      '"If I mess up again I\'ll lose my spot"',
      '"I should just play it safe from here"',
    ],
  },
  {
    id: 'pc5', n: 5, type: 'single',
    meta: 'Panic Cycle — Identity',
    q: 'Which phrase feels closest to your experience?',
    sub: 'Select one.',
    choices: [
      '"When I fail in sport I feel like I\'ve failed as a person"',
      '"I care deeply what my teammates think of me after mistakes"',
      '"I put enormous pressure on myself to be consistent every day"',
      '"My confidence depends a lot on how practice has been going"',
      '"I struggle to let go of mistakes and move on mid-game"',
    ],
  },
  {
    id: 'pc6', n: 6, type: 'multi', max: 2,
    meta: 'Panic Cycle — Body Response',
    q: 'What happens in your body?',
    sub: 'Choose up to two.',
    choices: [
      'Tight chest or shallow breathing',
      'Muscle tension or stiffness',
      'Heart racing or pounding',
      'Stomach drops or feels unsettled',
      'Legs feel heavy or slow',
      'I go through the motions — disconnected',
    ],
  },
  {
    id: 'pc7', n: 7, type: 'single',
    meta: 'Panic Cycle — Reaction',
    q: 'What emotional reaction usually shows up?',
    sub: 'Select one.',
    choices: [
      'I get frustrated and start forcing plays',
      'I go quiet and start hiding',
      'I get angry — at myself, teammates, or officials',
      'I start second-guessing every decision',
      'I try to overcompensate and do too much',
      'I shut down emotionally and go through the motions',
    ],
  },
  {
    id: 'pc8', n: 8, type: 'single',
    meta: 'Panic Cycle — Behavior',
    q: 'What do you usually do next?',
    sub: 'Select one.',
    choices: [
      'I stop calling for the ball / avoid being involved',
      'I hesitate and second-guess before acting',
      'I try to force a big play to make up for it',
      'I look to the bench or coach for reassurance',
      'I talk to myself negatively',
      'I take frustration out visibly (body language, reactions)',
    ],
  },
  {
    id: 'pc9', n: 9, type: 'text',
    meta: 'Panic Cycle — Your Pattern',
    q: 'In one sentence, what does this look like for you?',
    sub: 'e.g. "I stop calling for the ball and go quiet after a mistake."',
    placeholder: 'Write your sentence here...',
  },
  {
    id: 'pc10', n: 10, type: 'single',
    meta: 'Panic Cycle — Outcome',
    q: 'What usually happens after this sequence?',
    sub: 'Select one.',
    choices: [
      'My performance gets worse and the cycle continues',
      'I eventually reset on my own but it takes a while',
      'A teammate or coach snaps me out of it',
      'I shut down for the rest of the game',
      'I get subbed off or step back',
    ],
  },
  {
    id: 'pc11', n: 11, type: 'single',
    meta: 'Panic Cycle — Aftermath',
    q: 'How do you usually feel afterward?',
    sub: 'Select one.',
    choices: [
      'Disappointed in myself, replaying what went wrong',
      'Relieved it\'s over but worried it\'ll happen again',
      'Numb — I just try to forget it happened',
      'Motivated — I go extra hard in the next session',
      'Embarrassed and withdrawn from teammates',
    ],
  },
]

export const SM_QUESTIONS = [
  { id: 'sm1',  n: 12, meta: 'Social Map — Trust',               q: 'Who do you trust most to be honest and straightforward with you?',                              positive: true  },
  { id: 'sm2',  n: 13, meta: 'Social Map — Communication',        q: 'Who communicates in a way that helps you perform better or stay calm under pressure?',          positive: true  },
  { id: 'sm3',  n: 14, meta: 'Social Map — Safety',               q: 'Who do you feel most comfortable approaching when stressed or frustrated?',                     positive: true  },
  { id: 'sm4',  n: 15, meta: 'Social Map — Influence',            q: 'Whose attitude positively influences the team most?',                                            positive: true  },
  { id: 'sm5',  n: 16, meta: 'Social Map — Effectiveness',        q: 'Who do you work most effectively with during practices or games?',                               positive: true  },
  { id: 'sm6',  n: 17, meta: 'Social Map — Decision Trust',       q: 'Who do you trust to make good decisions in tough moments?',                                      positive: true  },
  { id: 'sm7',  n: 18, meta: 'Social Map — Understanding',        q: 'Who do you feel "gets you" — on and off the field?',                                             positive: true  },
  { id: 'sm8',  n: 19, meta: 'Social Map — Most Interaction',     q: 'Who do you interact with most during training, travel, and meetings?',                           positive: true  },
  { id: 'sm9',  n: 20, meta: 'Social Map — Positive Environment', q: 'Who contributes most to a positive team environment?',                                           positive: true  },
  { id: 'sm10', n: 21, meta: 'Social Map — Least Connected',      q: 'Who do you feel the least connected to on the team?',                                            positive: false, sub: 'Select up to 2. Confidential — helps identify athletes who may need more connection.' },
  { id: 'sm11', n: 22, meta: 'Social Map — Least Interaction',    q: 'Who do you tend to interact with the least?',                                                    positive: false },
  { id: 'sm12', n: 23, meta: 'Social Map — Hard to Communicate',  q: 'Who do you find it hardest to communicate with clearly or comfortably?',                        positive: false },
]
